import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Provider } from "@/components/provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style={{
        backgroundImage: `url(https://aiedgemarketing.com/_next/image/?url=https%3A%2F%2Faiedgemarketing.ditsmartehjem.dk%2Fwp-content%2Fuploads%2F2023%2F04%2FAI-Generated-Image.jpg&w=3840&q=75)`,
      }}
    >
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
